### ISSUE TITLE
DONE & TODO

### ISSUE THREAD

**Issue by suhyeokkim** [suhyeokkim/RenderFromScratch#1]
# graphic driver API
- [x] dx11 tutorial
- [x] import FBX
- [x] dx11 geometry load from FBX
- [x] dx11 skinning with FBX
- [ ] dx12 tutorial
- [ ] dx12 command managment by coroutine

# loader & serializer

- [ ] gltf

# early pipeline optimization
- [ ] frustom cull(oct/quad tree), sw occlusion cull, hi-z cull
- [ ] LOD rendering with culling
- [ ] LOD baking(opt)
- [ ] imposter baking
- [ ] imposter rendering
- [ ] apply merge strategy : buffer & texture(tiled resource)

# render light transport approximation
- [ ] shadow mapping for directional light
- [ ] shadow mapping for point light
- [ ] tiled rendering for massive lights(FPTL)
- [ ] apply single scattering microsurface BRDF
- [ ] subsurface scattering, screen-space

# bake lights
- [ ] irradiance volume
